name: "Sign Request"
description: "Sign a request body"
inputs:
  body:
    description: "The request body to sign. Can be a JSON string or a URL-encoded query string"
    required: true
    default: "key1=value1&key2=value2"
  secret:
    description: "Secret used to sign the request payload"
    required: true
    default: "very-secure-secret-change-me"
outputs:
  signature:
    description: 'The signature of the request payload. Prefixed with "sha256="'
  payload:
    description: "The original request body payload"
runs:
  using: "node16"
  main: "dist/index.js"
